package com.app.controller.v1;

import com.app.common.ApiConstants;
import com.app.enums.GitProviderType;
import com.app.model.repository.BranchModel;
import com.app.model.repository.PullRequestModel;
import com.app.model.repository.RepositoryModel;
import com.app.service.GitRepositoryService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;

@RestController
@RequestMapping(ApiConstants.API_V1 + "/repositories")
@RequiredArgsConstructor
@Tag(name = "V1 Git Repository Management Engine", description = "Git Repository, Branch & PR Management REST APIs")
public class V1RepositoryController {

    private final GitRepositoryService repositoryService;

    @PostMapping
    @Operation(summary = "Create or initialize a Git repository")
    public ResponseEntity<RepositoryModel> createRepository(@RequestBody Map<String, String> body) {
        String name = body.getOrDefault("name", "sample-repo");
        String providerStr = body.getOrDefault("provider", "GITHUB");
        GitProviderType provider = GitProviderType.valueOf(providerStr);

        return ResponseEntity.ok(repositoryService.createRepository(name, provider));
    }

    @GetMapping("/{id}")
    @Operation(summary = "Get repository details by ID")
    public ResponseEntity<RepositoryModel> getRepository(@PathVariable String id) {
        return repositoryService.getRepository(id)
            .map(ResponseEntity::ok)
            .orElse(ResponseEntity.notFound().build());
    }

    @GetMapping("/{id}/branches")
    @Operation(summary = "List branches in a repository")
    public ResponseEntity<List<BranchModel>> listBranches(@PathVariable String id) {
        return ResponseEntity.ok(repositoryService.listBranches(id));
    }

    @PostMapping("/{id}/branches")
    @Operation(summary = "Create a new branch in a repository")
    public ResponseEntity<BranchModel> createBranch(@PathVariable String id, @RequestBody Map<String, String> body) {
        String branchName = body.getOrDefault("branchName", "feature/auto-branch");
        return ResponseEntity.ok(repositoryService.createBranch(id, branchName));
    }

    @PostMapping("/{id}/pull-requests")
    @Operation(summary = "Create a pull request for code changes")
    public ResponseEntity<PullRequestModel> createPullRequest(@PathVariable String id, @RequestBody Map<String, String> body) {
        String title = body.getOrDefault("title", "Autonomous Feature Implementation");
        String description = body.getOrDefault("description", "Automated pull request generated by AI-COS");
        String sourceBranch = body.getOrDefault("sourceBranch", "feature/auto-branch");
        String targetBranch = body.getOrDefault("targetBranch", "main");

        return ResponseEntity.ok(repositoryService.createPullRequest(id, title, description, sourceBranch, targetBranch));
    }
}
